os:
- linux
- osx
language: node_js
node_js:
- node
- '8'
- '6'
env:
  global:
  - secure: A6BEfVYrazQFakPl1EAnHW/ep8UwHATXgDPnuUBZr1eRFxNv2sRZc+r6RsM2kzeH9QxhPyQBMv79O15amOFeDrBKQzAAMUrKOpb4Bl4wJBNxW4o1pdPlL2brUj7AjT1wjuQ/iztn96girb8QfWLD/d1D9D71U/jiyhQKxaL2nn150XwxP5wVzrNiodelIAnR6dOs+HEK2/no/tAzH3v6XhnnWh7sHcn39RByC3SmTw+VKN3CTnTJECyCHDMYfgLFA99yiExVfxDv1vEXRfQONdWrwkDeI3co3npfoK5i/xRk9D1mHJze45E8L3Nn2tDTFUqxY2tQIEkysP1ujXG9yATQ+Slq6+VTuK91Wg6WYTa3PSFC2ApRpujDi9gkL51wH1byfHbevFBnaumi1I9VwFGubsRUEsIVoukIQNd4BiNw9gKPmhrMl8UUOFxC/Wstu9/c5ZDPKyRiENPzy4INQTUrGdpYnZIILQ3fBQ5Rb9BBhbSnt8onLqZlTJ2gBz7BZ/TBharZ6HKrqsr2IyBDkaNDHFD9bewKgW8CLbT1ZXTaELUsm+PKqF79DmE7sdiYM+JLCyL13djC2jo7YFRvsusT3WnpqWYFXUw/UMnlfjGK187EJLfFFYF96P2IFrFQfoulJeEJXiZQDkEPaz3RoEhdssQd2kXgSm+t9prSAA8=
  - secure: m7FG+2TWK4GHamhNHd2cTz8/Mmthg1hA1830YEc8JMRdHWXbBdKBx7sO7dsFoNwULNf5MeBXrq+ma53BrkSctsQYhNyJiI2xua016thvFnGoWAd3LAYCBp5huBrLhtxHPtvRqk4JqJQ1tgcRkzrm3iDa2Um0bDEojcLc3Tq15eEOojuvoI8tc4+rXP573nmR4z4uVqw3OO0MuOIECGsFhxXP8YNL3eBN8adfOEJlts0mMnDTmqRfMfHVy35F39Ors1ZahaXxboGGy/v+er6XAFPyfiGiQT86pyqZxukpsFbqteF9b8hRil8wyxUAyIlOO9VcqBDzQy2dA5IoAR8PBIgl2RmnYOEAHZqsCCiNPae1M42vt+ODFAiZQAPwjTKt+UsBeO2HuklxXZSsU8pc7nJmT+o7fQcpxXJR6Bpf1y8VIvOIIXq2IMNm7+3lc/tAYedbkFNHD99TF5ttSXo5PHcdRoVztGfjCfZuCsdD+rZu6TcXi3mzkXHPNdYhWwDV9CpWowPrMZAsHdaXcHi20UqjiPnnz1OWHg+Ck4Yn3Jw2NQg7T893Hg7ND7kIjNyJA7YpDSNShjWPFf65cQxcGonSJ4fgtF8lirZAH0rwiPTEPjY9ItJpwx1ayjlQirdzcNW8Mvu8mK6p6M5azM8on0KPzYIHKTM1mWqjIHhhc88=
